feat: Add lecture review page
BCSDLab/HANGANG_WEB pull request #2
Opened 2021-01-10 13:31 UTC by YeomJaeSeon

## 주의 사항

- 최소 1명 이상의 assign을 받아야만 Merge가능합니다.

## 변경 사항

- 강의평가 페이지 추가

## 셀프 체크리스트

- [x] warning message가 발생하지 않나요?
- [x] 코드 컨벤션을 지켰나요?
- [x] `npm run lint`나 `yarn lint`를 실행하였나요?

2021-01-10 15:48 UTC, SimYunSup requested changes
종합적으로 고쳐야 할 부분이 많습니다.
- zeplin에 있는 코드 복사 붙여넣기 하지 마시고 할거라면 계산해가면서 복사 붙여넣기하세요.
- 디자인을 무시하면서 코딩하시면 안됩니다. 디자인하고 비교해가면서 퍼블리싱하세요.
- props를 display용도로만 사용하실 거라면 children을 사용하세요.
- Star 구현은 잘 하셨으나 재사용성을 위해 제가 리팩토링하겠습니다.

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/SelectReview/SelectReview.tsx
> +  const selectOption = () => {
onSelect를 props로 받고 selectOption을 굳이 또 만들지 않게 input태그의 value를 활용해서 다시 짜보세요. 지금의 형태는 재사용성이 떨어집니다.

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/SelectReview/SelectReview.tsx
> +  reviewData: { id: number; value: string };
value를 props로 넘기지 않고 children으로 보내는 것이 좋습니다. 지금의 형태에서는 display용도로만 쓰이니까요.

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/ReviewTitle/ReviewTitle.tsx
> +    {metadata && <ReviewTitleMetaData totalReview={metadata === '아직 작성이 완료되지 않았습니다.'}>{metadata}</ReviewTitleMetaData>}
경고 svg가 없습니다.

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/HashTag/HashTag.tsx
> +];
selected 지워주시길 바랍니다

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/HashTag/HashTag.tsx
> +          isSelected={selectedReview.some((id) => id === data.id)}
`some`메소드를 사용하시지 마시고 `includes`를 사용하세요

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/AssignmentInfo/AssignmentInfo.tsx
> +            isSelected={selectedReview.some((id) => id === data.id)}
`some`메소드를 사용하시지 마시고 `includes`를 사용하세요

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/AssignmentAmount/AssignmentAmount.tsx
> +      <div>
`div`로 감싸야 한다면 해당 `div`에 이름을 지어주시고, 아니라면 `React.Fragment`를 사용하세요.

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/TotalReview/TotalReview.tsx
> +          placeholder="이 강의에 대한 총평을 자유롭게 적어주세요!&#13;&#10;(시험정보, 과제정보, 팁 등)&#13;&#10;허위사실이나 지나친 비방 내용을 작성할 시,&#13;&#10;승인이 불가할 수 있습니다."
동적으로 placeholder를 관리하는 것이 아니면 style 폴더로 옮겨주세요.

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/TotalReview/TotalReviewComment.style.ts
> +  font-weight : bold;
`greyFontColor` > `mainFontColor`, `bold` > `normal`

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/TotalReview/TotalReviewComment.style.ts
> +  :-ms-input-placeholder {
굳이 하실 필요 없습니다. styled-components가 해줍니다.

2021-01-10 15:48 UTC, SimYunSup commented on src/pages/index.js
> +export default index;
회의 이후 올바른 폴더로 옮겨주세요.

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/SelectReview/SelectReview.style.ts
> +  margin: 16px 8px 32px 8px;
디자인에 맞게 다시 작성하시길 바랍니다.

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/ReviewTitle/ReviewTitle.style.ts
> +  margin: 16px 5px 16px 8px;
디자인에 맞게 바꾸시길 바랍니다. zeplin 복사붙여넣기 하신 것 같은데. 계산하고 넣어야 합니다.

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/TotalReview/TotalReview.tsx
> +      <ReviewTitle title="총평" metadata={!commentReview ? '아직 작성이 완료되지 않았습니다.' : null} />
해당 타이틀은 따로 관리해주세요. 폰트 크기 다릅니다.

2021-01-10 15:48 UTC, SimYunSup commented on src/components/LectureReview/ReviewTitle/ReviewTitle.style.ts
> +export const ReviewTitleMetaData = styled.h2<StylePropType>`
해당 form의 타이틀 옆에 있는 정보 표시인데 Title보다 heading이 크네요. 그리고 heading 태그를 쓰면 자동으로 `bold`처리가 됩니다.

2021-01-13 10:13 UTC, YeomJaeSeon reviewed
수강학기 선택하는 부분도 select태그를 이용해서 커스터마이즈 했습니다.
Semester 컴포넌트의 state같은 부분은 기존 다른 컴포넌트들(출첵빈도,과제정보..)등과같은 방식으로 '일단은'설정했습니다. (만약 2020년 2학기가되면 프론트에서 직접 추가해야하나? 등등을 잘몰라서..)

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/AssignmentInfo/AssignmentInfo.tsx
> +            isSelected={selectedReview.some((id) => id === data.id)}
some -> includes 수정했습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/HashTag/HashTag.tsx
> +];
불필요한 selected 삭제하였습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/HashTag/HashTag.tsx
> +          isSelected={selectedReview.some((id) => id === data.id)}
HashTag 컴포넌트에서도 some대신 includes 메소드로 변경하였습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/AssignmentAmount/AssignmentAmount.tsx
> +      <div>
단순히 wrapper만을위해서 사용한 불필요한 `div` 들을 모든 컴포넌트에서 React.Fragment로 변경하였습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/ReviewTitle/ReviewTitle.style.ts
> +export const ReviewTitleMetaData = styled.h2<StylePropType>`
둘다 span으로 변경하였고 Title의 font-weight을 제플린과 같이 500을 주었습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/SelectReview/SelectReview.tsx
> +  reviewData: { id: number; value: string };
단순히 display만을 위해서 props로 전달한 string들은 재사용성이 떨어지므로 props.children을 이용해서 전달하는걸로 변경했습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/TotalReview/TotalReview.tsx
> +      <ReviewTitle title="총평" metadata={!commentReview ? '아직 작성이 완료되지 않았습니다.' : null} />
과제정보, 해시태그의 메타데이터 ('중복선택', '1~3개 선택')과 총평의 메타데이터('아직작성이완료되지않았습니다') 폰트사이즈가 다르므로 16px, 15px(1px차이)로 각각 변경하였습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/TotalReview/TotalReviewComment.style.ts
> +  font-weight : bold;
강의평 작성 완료 제플린을 확인하지 못하여서 (작성 중만 확인함.) 수정을 못했습니다. 맞게 수정했습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/TotalReview/TotalReviewComment.style.ts
> +  :-ms-input-placeholder {
삭제하였습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/pages/index.js
> +export default index;
/lectures/register.tsx 파일로 이동시켰고 import export를 single라인으로 안하고
```
/lectures/register.tsx
import LectureReview from '@views/LectureReview/LectureReview';
export default LectureReview;
```
로 변경하였습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/SelectReview/SelectReview.tsx
> +  const selectOption = () => {
selectOption으로 id를 단순히 전달하기보단 input태그의 value에 reviewId를 넣어서 onChange이벤트가 일어날때마다 input의 value값을 전달하게 변경하였습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/ReviewTitle/ReviewTitle.tsx
> +    {metadata && <ReviewTitleMetaData totalReview={metadata === '아직 작성이 완료되지 않았습니다.'}>{metadata}</ReviewTitleMetaData>}
추가했습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/TotalReview/TotalReview.tsx
> +          placeholder="이 강의에 대한 총평을 자유롭게 적어주세요!&#13;&#10;(시험정보, 과제정보, 팁 등)&#13;&#10;허위사실이나 지나친 비방 내용을 작성할 시,&#13;&#10;승인이 불가할 수 있습니다."
이부분이 이해가잘가지 않는데.
style 폴더라하면 style관련 폴더인가요?
그렇다면 textArea인 CommentBox컴포넌트 자체를 style폴더로 보내야하는건가요?
아니면 placeholder에 대한 내용만 style로 보내는 건가요?

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/ReviewTitle/ReviewTitle.style.ts
> +  margin: 16px 5px 16px 8px;
css에대한 전체적인 균형을 다시잡았습니다.

2021-01-13 10:13 UTC, YeomJaeSeon commented on src/components/LectureReview/SelectReview/SelectReview.style.ts
> +  margin: 16px 8px 32px 8px;
css다시 작성하였습니다. - 균형이 맞도록

2021-01-13 11:50 UTC, SimYunSup requested changes
리뷰 이외에도 CSS를 전체적으로 변경해주세요.

2021-01-13 11:50 UTC, SimYunSup commented on src/components/LectureReview/SelectReview/SelectReview.tsx
> +    />
이전하고 달라진 점이 없습니다. onChange함수를 컴포넌트 안에서 다시 선언하는 것이 타당하다고 생각하시면 댓글을 달아주세요.

2021-01-13 11:50 UTC, SimYunSup commented on src/pages/index.js
> +import LectureReview from '@views/LectureReview/LectureReview';
그냥 index.js를 없애세요

2021-01-13 11:50 UTC, SimYunSup commented on src/pages/lectures/register.tsx
> +export default LectureReview;
`export { default } from '@views/LectureReview/LectureReview';`로 줄일 수 있습니다.

2021-01-13 11:50 UTC, SimYunSup commented on src/style/style.ts
> +export default LectureReviewCommentPlaceholder;
이전의 style폴더로 옮겨달라는 것은 `해당 컴포넌트.style.ts`로 옮겨달라는 뜻이였습니다. 혼란을 일으키는 말 쓴 것 죄송합니다. styled-components의 attrs를 사용해서 넣어주시길 바랍니다.

2021-01-13 11:50 UTC, SimYunSup commented on src/components/LectureReview/SelectReview/SelectReview.style.ts
>    background-color: ${({ selected }) => (selected ? style.mainColor : style.greyBackgroundColor)};
확인하셨는지는 모르겠지만 모바일 화면에서 버튼의 위치가 모두 이상합니다.

2021-01-13 11:50 UTC, SimYunSup commented on src/components/LectureReview/SelectReview/SelectReview.style.ts
>    background-color: ${({ selected }) => (selected ? style.mainColor : style.greyBackgroundColor)};
너비 360px 기준으로 css가 정확하게 나와야 합니다.

2021-01-13 11:50 UTC, SimYunSup commented on src/components/LectureReview/TotalReview/TotalReview.tsx
> +      <ReviewTitle title="총평" metadata={!commentReview ? '아직 작성이 완료되지 않았습니다.' : null} />
`ReviewTitle`로 관리하지 마시고 style 가져와서 따로 관리해주세요.

2021-01-13 11:50 UTC, SimYunSup commented on src/components/LectureReview/TotalReview/TotalReviewComment.style.ts
>    background-color: #f5f5f5;
색깔이 없으면 `css-util`에 추가해 주시고, 있으면 가져와서 쓰세요.

2021-01-13 11:58 UTC, YeomJaeSeon commented on src/components/LectureReview/SelectReview/SelectReview.style.ts
>    background-color: ${({ selected }) => (selected ? style.mainColor : style.greyBackgroundColor)};
너비 576px 기준아닌가요? 그래서 576px에 모두맞춰서했는데.

2021-01-13 12:02 UTC, SimYunSup commented on src/components/LectureReview/SelectReview/SelectReview.style.ts
>    background-color: ${({ selected }) => (selected ? style.mainColor : style.greyBackgroundColor)};
아닙니다. 576px에서 바뀐다고 576px이 기준이 아닙니다. 576px을 기준으로 모든 크기를 임의로 재구성 하신거 같은데, 이렇게 하면 모든 모바일 화면에서 깨집니다. 360px을 기준으로 디자인이 맞춰져있기 때문에 360px~576px에서 잘 작동해야 합니다. 576px에서만 작동 가능한게 아니라요.

2021-01-13 12:05 UTC, SimYunSup commented on src/components/LectureReview/SelectReview/SelectReview.style.ts
>    background-color: ${({ selected }) => (selected ? style.mainColor : style.greyBackgroundColor)};
제플린의 폰트, 너비, 높이를 가져와서 모두 다시 바꿔주세요.

2021-01-13 15:18 UTC, YeomJaeSeon commented on src/components/LectureReview/SelectReview/SelectReview.style.ts
>    background-color: ${({ selected }) => (selected ? style.mainColor : style.greyBackgroundColor)};
아 알겠습니다. 수정할게요 감사합니다.

2021-01-14 06:58 UTC, YeomJaeSeon commented on src/components/LectureReview/SelectReview/SelectReview.tsx
> +    />
저는 각각의 체크박스를 클릭했을 때 상위컴포넌트의 select함수가 실행되도록하여 선택된 체크박스의 id를 State로 관리하였습니다. 그래서 각각의 체크박스 컴포넌트를 눌렀을때 해당 체크박스 컴포넌트의 id를 넘겨줘야하기 때문에 onChange함수를 체크박스 컴포넌트에서 다시선언하여 id를 넘겨주었습니다.
즉, 상위컴포넌트의 select함수를(리뷰 선택하는 함수) onSelect props로 전달하였고 이 onSelect함수를 통해서 체크박스 컴포넌트와 상위컴포넌트간 id를 주고받을수있도록 하였기에 이렇게 만들었습니다.

상위컴포넌트에게 해당 체크박스컴포넌트(자식컴포넌트)가 받은 props를 다시 상위컴포넌트에게 넘길수있는 방법이 이외에 존재하는지 잘모르겠습니다. (윤섭님이 힌트주신 input value를 이용해라.)

상위컴포넌트랑 하위컴포넌트간에 select - onSelect로 이어져있어 재사용성이 떨어지는것 같긴한데 이방법외에는 생각이 나질않아서 질문드립니다.

2021-01-16 10:02 UTC, SimYunSup commented on src/components/LectureReview/SelectReview/SelectReview.tsx
> +    />
답변 늦어진 점 죄송합니다. `onChange`에서 이용한 대로 props로 받는 `onSelect`함수를 `(e: React.ChangeEvent) => void`로 받는 방식으로 작성을 해보시길 바랍니다.

2021-01-18 09:14 UTC, SimYunSup approved these changes
LGTM.

2021-01-18 09:15 UTC, merged