feat: Add shared components
BCSDLab/HANGANG_WEB pull request #5
Opened 2021-01-25 07:34 UTC by YeomJaeSeon

## 주의 사항

- 최소 1명 이상의 assign을 받아야만 Merge가능합니다.

## 변경 사항

- change 

## 셀프 체크리스트

- [x] warning message가 발생하지 않나요?
- [x] 코드 컨벤션을 지켰나요?
- [x] `npm run lint`나 `yarn lint`를 실행하였나요?

2021-01-26 11:59 UTC, SimYunSup requested changes
바꾸신 후 커밋하시면 됩니다.

2021-01-29 14:52 UTC, SimYunSup requested changes
바꿀 점을 다시 리뷰했습니다.

2021-01-29 14:52 UTC, SimYunSup commented on src/components/Shared/BottomNav/BottomNav.style.ts
> +  selected : boolean;
`selected`를 한 곳에서만 넣도록 바꾸세요.

2021-01-29 14:52 UTC, SimYunSup commented on src/components/Shared/TopNav/index.tsx
> +  Metadata ?: JSX.Element;
대문자로 쓰신 이유라도 있을까요? 그리고 `JSX.Element`가 아닌 `React.ReactNode`를 사용하기를 추천합니다.
https://github.com/typescript-cheatsheets/react#useful-react-prop-type-examples

2021-01-29 14:52 UTC, SimYunSup commented on src/pages/lectures/index.tsx
> +// BottomNav test
지우세요

2021-01-29 14:52 UTC, SimYunSup commented on src/views/LecturePages/LectureDetailPage/index.tsx
> +    />
테스트용도로 만드신거 같은데 적용하시지 않을 거라면 지우세요.

2021-01-29 14:52 UTC, SimYunSup commented on src/views/LecturePages/LectureDetailPage/index.tsx
> +import { SubOptionButton } from '@components/Shared/TopNav/TopNav.style';
Button은 따로 관리하게 두세요.

2021-01-29 14:52 UTC, SimYunSup commented on src/components/Shared/DefaultLayout/index.tsx
> +    {children}
주석을 달지 않은 점은 죄송합니다. 해당 컴포넌트는 header와 bottomnav가 담긴 공유 컴포넌트로 만들려고 했습니다. 돌려놓아주세요.

2021-01-29 15:24 UTC, YeomJaeSeon commented on src/components/Shared/TopNav/index.tsx
> +  Metadata ?: JSX.Element;
컴포넌트를 받기때문에 굳이 대문자로 썼습니다.

2021-01-29 15:36 UTC, YeomJaeSeon commented on src/components/Shared/DefaultLayout/index.tsx
> +    {children}
DefaultLayout에 header와 bottomnav 컴포넌트를 놓으라는 말씀이신가요? 아니면 제가 작업중 테스트한다고 DefaultLayout을 건들었는데 지워달란 말씀이신가요?

2021-01-29 15:36 UTC, YeomJaeSeon commented on src/components/Shared/TopNav/index.tsx
> +  Metadata ?: JSX.Element;
상관없으면 다른 props들과같이 소문자로 바꾸겠습니다.

2021-01-31 10:35 UTC, SimYunSup commented on src/components/Shared/DefaultLayout/index.tsx
> +    {children}
`DefaultLayout`을 이전 버전으로 돌려놓아주세요. 후에 API연동할때 수정할 예정입니다.

2021-02-01 15:44 UTC, SimYunSup requested changes
깜빡하고 CSS부분을 검토를 못했네요. CSS부분도 다시 바꿔주시면 되겠습니다.

2021-02-01 15:44 UTC, SimYunSup commented on src/components/Shared/Header/Header.style.ts
> +    background-color: transparent;
`position: absolute`가 아닌 `HeaderContainer`에 `display: flex`와 `padding`을 사용해서 해결해보세요.

2021-02-01 15:44 UTC, SimYunSup commented on src/components/Shared/Header/Header.style.ts
> +    height: 72px;
모바일 헤더의 높이는 코인과 같게 `56px`로 해주세요.

2021-02-01 15:44 UTC, SimYunSup commented on src/components/Shared/BottomNav/BottomNav.style.ts
> +}
`BottomNav`를 넣은 `/lectures`페이지를 만들어서 브라우저에서 DOM분석기를 보면 `selected`라는 DOM 속성이 `true`로 렌더링 된 버튼이 하나가 있을겁니다. 이는 충분히 오류를 발생할 수 있습니다(물론 기존의 `selected`라는 속성은 boolean이라 오류를 발생하지 않을겁니다.). 그래서 `selected`를 `$selected`로 변경하라고 리뷰를 해드렸구요.

2021-02-01 15:44 UTC, SimYunSup commented on src/components/Shared/BottomNav/BottomNav.style.ts
> +`;
해당 DOM을 지우고 `NavContainer`에 `display: flex`를 넣고 `NavOption`에 `flex: 1 1 0`을 넣고 이 태그를 지우시고 `NavOption`의 `border`로 대체해보세요. 애니메이션을 넣을 생각이였다면 다른 방향을 제시했겠지만 아닌 것 같네요.

2021-07-10 02:27 UTC, SimYunSup approved these changes

2021-07-10 02:27 UTC, merged